version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: /tmp/my-project
    filters:
      branches:
        only: master
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Gatsby build site
          command: yarn build
      - run:
          name: Run deploy scripts
          command: chmod +x .scripts/deploy.sh && .scripts/deploy.sh public
