version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Gatsby build site
          command: yarn build
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Run deploy scripts
          command: chmod +x ~/project/.scripts/deploy.sh && ~/project/.scripts/deploy.sh public

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
